cmd_/home/ubuntu/rtl8812au/platform/platform_ops.o := arm-linux-gnueabihf-gcc -Wp,-MD,/home/ubuntu/rtl8812au/platform/.platform_ops.o.d  -nostdinc -isystem /root/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian/bin/../lib/gcc/arm-linux-gnueabihf/4.8.3/include -I./arch/arm/include -I./arch/arm/include/generated/uapi -I./arch/arm/include/generated  -I./include -I./arch/arm/include/uapi -I./include/uapi -I./include/generated/uapi -include ./include/linux/kconfig.h -D__KERNEL__ -mlittle-endian -Wall -Wundef -Wstrict-prototypes -Wno-trigraphs -fno-strict-aliasing -fno-common -Werror-implicit-function-declaration -Wno-format-security -std=gnu89 -fno-PIE -fno-dwarf2-cfi-asm -fno-omit-frame-pointer -mapcs -mno-sched-prolog -fno-ipa-sra -mabi=aapcs-linux -mno-thumb-interwork -mfpu=vfp -funwind-tables -marm -D__LINUX_ARM_ARCH__=6 -march=armv6k -mtune=arm1136j-s -msoft-float -Uarm -fno-delete-null-pointer-checks -O2 -Wno-maybe-uninitialized --param=allow-store-data-races=0 -DCC_HAVE_ASM_GOTO -Wframe-larger-than=1024 -fno-stack-protector -Wno-unused-but-set-variable -fno-omit-frame-pointer -fno-optimize-sibling-calls -fno-var-tracking-assignments -pg -Wdeclaration-after-statement -Wno-pointer-sign -fno-strict-overflow -fno-stack-check -fconserve-stack -Werror=implicit-int -Werror=strict-prototypes -O1 -Wno-unused-variable -Wno-unused-value -Wno-unused-label -Wno-unused-parameter -Wno-unused-function -Wno-unused -I/home/ubuntu/rtl8812au/include -I/home/ubuntu/rtl8812au/hal/phydm -DDBG=0 -I/home/ubuntu/rtl8812au/platform -DCONFIG_RTL8812A -DCONFIG_RTL8821A -DCONFIG_MP_INCLUDED -DCONFIG_TRAFFIC_PROTECT -DCONFIG_RTW_ADAPTIVITY_EN=0 -DCONFIG_RTW_ADAPTIVITY_MODE=0 -DCONFIG_BR_EXT '-DCONFIG_BR_EXT_BRNAME="'br0'"' -DCONFIG_WIFI_MONITOR -DDM_ODM_SUPPORT_TYPE=0x04 -DCONFIG_LITTLE_ENDIAN -DCONFIG_IOCTL_CFG80211 -DRTW_USE_CFG80211_STA_EVENT  -DMODULE  -DKBUILD_BASENAME='"platform_ops"'  -DKBUILD_MODNAME='"8812au"' -c -o /home/ubuntu/rtl8812au/platform/.tmp_platform_ops.o /home/ubuntu/rtl8812au/platform/platform_ops.c

source_/home/ubuntu/rtl8812au/platform/platform_ops.o := /home/ubuntu/rtl8812au/platform/platform_ops.c

deps_/home/ubuntu/rtl8812au/platform/platform_ops.o := \
    $(wildcard include/config/platform/ops.h) \

/home/ubuntu/rtl8812au/platform/platform_ops.o: $(deps_/home/ubuntu/rtl8812au/platform/platform_ops.o)

$(deps_/home/ubuntu/rtl8812au/platform/platform_ops.o):
